stages:
  - test
  - prod_build_push
  - prod_deploy



Test CodeBase with SonarQube:
  stage: test
  image: sonarsource/sonar-scanner-cli:${SONAR_SCANNER_CLI_VERSION}
  variables:
    SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
    GIT_DEPTH: 0
  script:
    - /usr/bin/entrypoint.sh sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - main
    - develop
  tags:
    - docker-build


kubernetes prod build push:
  stage: prod_build_push
  variables:
    GIT_STRATEGY: clone
  #   GIT_SUBMODULE_STRATEGY: normal
  script:
    - cat $ENV_PROD > .env.local
    - git checkout $CI_COMMIT_REF_NAME
    - sudo docker build -t registry.digitalocean.com/mineplex-registry/agilitycms-prod:$CI_COMMIT_SHORT_SHA .
    - sudo docker push registry.digitalocean.com/mineplex-registry/agilitycms-prod:$CI_COMMIT_SHORT_SHA
  only:
    - main
  tags:
    - shell-build

kubernetes prod deploy:
  stage: prod_deploy
  script:
    - sudo kubectl set image deployment/agilitycms-prod  agilitycms-prod=registry.digitalocean.com/mineplex-registry/agilitycms-prod:$CI_COMMIT_SHORT_SHA --namespace=scrump-prod
  only:
    - main
  tags:
    - shell-build
